#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# presets
bash $HOME/.config/bspwm/presets.sh
/vuesax/linear/vuesax/linear
bspc monitor -d I II III IV V

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name spider
