#!/bin/bash

xset r rate 210 40

#autostart flameshot
flameshot &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height	  0
berryc top_gap            30

# Set decoration colors
berryc focus_color         89CFF0
berryc unfocus_color       292D3E
berryc inner_focus_color   89CFF0   
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"

berryc move_mask "mod4"
berryc move_button 1

berryc resize_mask "mod1"
berryc resize_button 1


berryc title_height 1

libinput-gestures-setup autostart start
~/.fehbg &
polybar
wal -ni /home/maintheme/style/theme/blue-r33.jpg
